package br.edu.ifpr.ui;

import br.edu.ifpr.patterns.command.Command;
import br.edu.ifpr.patterns.factory.CommandFactory;
import br.edu.ifpr.patterns.factory.CommandFactoryProperties;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author  Romualdo Rubens de Freitas
 */
@SuppressWarnings("serial")
public class VendaFrame extends javax.swing.JFrame {
   private ProcessarVenda pv = new ProcessarVenda();
   private CommandFactory cf = new CommandFactoryProperties();

   /** Creates new form VendaFrame */
   public VendaFrame() {
      initComponents();
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jButton1.setText("Nova Venda");

      jButton2.setText("Aprovar Venda");

      jButton3.setText("Finalizar Venda");

      jButton4.setText("Cancelar Venda");

      jTextArea1.setColumns(20);
      jTextArea1.setRows(5);
      jScrollPane1.setViewportView(jTextArea1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jButton1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGap(6, 6, 6)
                  .addComponent(jButton3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton4)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jButton1.setActionCommand(CommandFactory.NOVA_VENDA);
      jButton1.addActionListener(pv);
      jButton2.setActionCommand(CommandFactory.APROVAR_VENDA);
      jButton2.addActionListener(pv);
      jButton3.setActionCommand(CommandFactory.FINALIZAR_VENDA);
      jButton3.addActionListener(pv);
      jButton4.setActionCommand(CommandFactory.CANCELAR_VENDA);
      jButton4.addActionListener(pv);

      java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
      setBounds((screenSize.width-454)/2, (screenSize.height-173)/2, 454, 173);
   }// </editor-fold>//GEN-END:initComponents
   
      /**
    * @param args the command line arguments
    *
   public static void main(String args[]) {
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new VendaFrame().setVisible(true);
         }
      });
   }
    */
   
   private class ProcessarVenda implements ActionListener {
      public void actionPerformed(ActionEvent e) {
         String commandAction = e.getActionCommand();
         jTextArea1.append("Command: " + commandAction + "\n");
         Command command = cf.createCommandFactory(commandAction);
         command.execute();
      } // public void actionPerformed(ActionEvent)
   } // private ProcessarVenda implements ActionListener

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextArea1;
   // End of variables declaration//GEN-END:variables
   
}
